import ast


node_children = {
    ast.Constant: [],
    ast.Pass: [],
    type(None): [],
    ast.Name: [],
    ast.Starred: ["value"],
    ast.Delete: ["targets"],
    ast.Module: ["body"],
    ast.Assign: ["targets", "value"],
    ast.AugAssign: ["target", "value"],
    ast.AnnAssign: ["target", "annotation", "value"],
    ast.Expression: ["body"],
    ast.Expr: ["value"],
    ast.Import: ["names"],
    ast.ImportFrom: ["names"],
    ast.alias: [],
    ast.ClassDef: ["bases", "keywords", "decorator_list", "body"],
    ast.Attribute: ["value"],
    ast.FunctionDef: ["decorator_list", "args", "body", "returns", "type_comment"],
    ast.AsyncFunctionDef: ["decorator_list", "args", "body", "returns", "type_comment"],
    ast.Await: ["value"],
    ast.Lambda: ["args", "body"],
    ast.arg: [],
    ast.arguments: [
        "posonlyargs",
        "args",
        "vararg",
        "kwonlyargs",
        "kwarg",
        "defaults",
        "kw_defaults",
    ],
    ast.Global: [],
    ast.Nonlocal: [],
    ast.Return: ["value"],
    ast.Yield: ["value"],
    ast.YieldFrom: ["value"],
    ast.Call: ["func", "args", "keywords"],
    ast.keyword: ["value"],
    ast.If: ["test", "body", "orelse"],
    ast.IfExp: ["test", "body", "orelse"],
    ast.While: ["test", "body", "orelse"],
    ast.For: ["target", "iter", "body", "orelse"],
    ast.Break: [],
    ast.Continue: [],
    ast.With: ["items", "body"],
    ast.withitem: ["context_expr", "optional_vars"],
    ast.Raise: ["exc", "cause"],
    ast.Assert: ["test", "msg"],
    ast.Try: ["body", "handlers", "orelse", "finalbody"],
    ast.ExceptHandler: ["type", "body"],
    ast.Tuple: ["elts"],
    ast.List: ["elts"],
    ast.Set: ["elts"],
    ast.Dict: ["keys", "values"],
    ast.ListComp: ["elt", "generators"],
    ast.SetComp: ["elt", "generators"],
    ast.DictComp: ["key", "value", "generators"],
    ast.GeneratorExp: ["elt", "generators"],
    ast.comprehension: ["target", "iter", "ifs"],
    ast.JoinedStr: ["values"],
    ast.FormattedValue: ["value"],
    ast.Subscript: ["value", "slice"],
    ast.Index: ["value"],
    ast.Slice: ["lower", "upper", "step"],
    ast.ExtSlice: ["dims"],
    ast.UnaryOp: ["operand"],
    ast.BinOp: ["left", "right"],
    ast.BoolOp: ["values"],
    ast.Compare: ["left", "comparators"],
}

string_children = {
    ast.Name: ["id"],
    ast.ImportFrom: ["module"],
    ast.alias: ["name", "asname"],
    ast.ClassDef: ["name"],
    ast.Attribute: ["attr"],
    ast.FunctionDef: ["name"],
    ast.AsyncFunctionDef: ["name"],
    ast.arg: ["arg"],
    ast.ExceptHandler: ["name"],
}  # TODO: ast.Global has names, which is a list

node_types = set(node_children.keys()) | set(string_children.keys())
leaf_types = {
    node_type for node_type, children in node_children.items() if len(children) == 0
}
